apiVersion: v1
kind: Service
metadata:
  name: apache-lb-service
spec:
  type: LoadBalancer
  selector:
    app: apache-app     # same label set for PODs on deployment template
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
 # externalTrafficPolicy: Local
